Remove methode services
Financial-Times/upp-aggregate-healthcheck pull request #76
Opened 2021-11-26 09:45 UTC by StephanZahariev

# Description

## What

Remove methode services

## Why

[UPPSF-2820](https://financialtimes.atlassian.net/browse/UPPSF-2820)

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [X] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-11-26 10:45 UTC, martin-stanchev approved these changes
The changes are good!

Could you upgrade the module that is failing in the snyk check -> `gopkg.in/yaml.v2@2.2.4` to 2.2.8

2021-11-26 10:46 UTC, dbelev approved these changes

2021-11-26 12:50 UTC, StephanZahariev commented
> 

Unfortunately it is not a direct reference but a dependency from `k8s.io`. In any way I would prefer to have a separate PR for this since reverting will be easier.

```
$ go mod why gopkg.in/yaml.v2
# gopkg.in/yaml.v2
github.com/Financial-Times/upp-aggregate-healthcheck
k8s.io/apimachinery/pkg/apis/meta/v1
k8s.io/apimachinery/pkg/apis/meta/v1.test
github.com/ghodss/yaml
gopkg.in/yaml.v2
```

2021-11-26 15:02 UTC, atanasdinov requested changes
There are also the `binary-ingester`, `binary-writer`, `synthetic-article-publication-monitor` (not the "generic" one) we should be able to safely remove.

2021-11-30 07:37 UTC, dbelev approved these changes

2021-11-30 10:01 UTC, martin-stanchev approved these changes

2021-11-30 12:17 UTC, atanasdinov approved these changes

2022-01-04 12:09 UTC, merged